services:
  qix-mongo:
    image: mongo:latest
    container_name: qix-mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - qix-net
    restart: unless-stopped

  qix-redis:
    image: redis:alpine
    container_name: qix-redis
    networks:
      - qix-net
    restart: unless-stopped

  qix-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: qix-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - qix-mongo
      - qix-redis
    networks:
      - qix-net

  qix-web:
    build:
      context: ./qix-web
      dockerfile: Dockerfile.web
    container_name: qix-web
    restart: unless-stopped
    ports:
      - "5173:80"
    networks:
      - qix-net

  qix-shredder:
    build:
      context: ./workers
      dockerfile: Dockerfile.worker
    container_name: qix-shredder
    restart: unless-stopped
    depends_on:
      - qix-mongo
    networks:
      - qix-net

networks:
  qix-net:
    driver: bridge

volumes:
  mongo_data: