export const CHAT_THEMES = {
    dark_corridor: { id: 'dark_corridor', name: 'Abandoned Corridor', bg: '/themes/images/abandoneddirtycorridor.webp', bubbles: 'from-zinc-700 to-zinc-900', tags: ['dark', 'mysterious', 'urbex'] },
    dark_alley: { id: 'dark_alley', name: 'Charcoal Alley', bg: '/themes/images/darkalleywaymonochromecharcoaldrawing.webp', bubbles: 'from-slate-700 to-black', tags: ['dark', 'monochrome', 'art'] },
    shadow_corridor: { id: 'shadow_corridor', name: 'Distant Sunlight', bg: '/themes/images/darkcorridordistantsunlight.webp', bubbles: 'from-stone-700 to-stone-900', tags: ['dark', 'architecture', 'mysterious'] },
    dirty_window: { id: 'dirty_window', name: 'Grunge Window', bg: '/themes/images/darkdirtywindowmonochrome.webp', bubbles: 'from-gray-700 to-gray-950', tags: ['dark', 'monochrome', 'grunge'] },
    foggy_tunnel: { id: 'foggy_tunnel', name: 'Foggy Tunnel', bg: '/themes/images/foggyeveningtunneldark.webp', bubbles: 'from-indigo-900 to-slate-950', tags: ['dark', 'urban', 'mysterious'] },
    inside_tunnel: { id: 'inside_tunnel', name: 'The Depths', bg: '/themes/images/insidedarktunnel.webp', bubbles: 'from-neutral-700 to-neutral-950', tags: ['dark', 'urban', 'grunge'] },
    man_in_fog: { id: 'man_in_fog', name: 'Silhouette', bg: '/themes/images/manstandinginfogdarkmonochrome.webp', bubbles: 'from-slate-700 to-black', tags: ['dark', 'monochrome', 'mysterious'] },
    skulls_mono: { id: 'skulls_mono', name: 'Catacombs', bg: '/themes/images/skullsdarkmonochrome.webp', bubbles: 'from-zinc-700 to-zinc-950', tags: ['dark', 'monochrome', 'gothic'] },
    study_skull: { id: 'study_skull', name: 'Gothic Study', bg: '/themes/images/darkstudyskull.webp', bubbles: 'from-rose-900 to-red-950', tags: ['dark', 'gothic', 'mysterious'] },
    night_street: { id: 'night_street', name: 'Street Lamp', bg: '/themes/images/darknightstreetnightlamp.webp', bubbles: 'from-amber-700 to-orange-950', tags: ['dark', 'urban', 'night'] },
    dark_woman: { id: 'dark_woman', name: 'Noir Portrait', bg: '/themes/images/darkwomanmonochrome.webp', bubbles: 'from-zinc-600 to-zinc-900', tags: ['dark', 'monochrome', 'portrait'] },
    dark_clouds: { id: 'dark_clouds', name: 'Ominous Sky', bg: '/themes/images/darkclouds.webp', bubbles: 'from-slate-700 to-slate-950', tags: ['dark', 'sky', 'moody'] },
    melancholic_man: { id: 'melancholic_man', name: 'Charcoal Portrait', bg: '/themes/images/darkmelancholicmancharcoaldrawing.webp', bubbles: 'from-neutral-700 to-black', tags: ['dark', 'art', 'monochrome'] },
    dark_room_window: { id: 'dark_room_window', name: 'Shadowed Room', bg: '/themes/images/darkroomwindowmonochrome.webp', bubbles: 'from-gray-700 to-black', tags: ['dark', 'monochrome', 'mysterious'] },
    dark_window_room: { id: 'dark_window_room', name: 'Window Light', bg: '/themes/images/darkwindowroommonochrome.webp', bubbles: 'from-zinc-700 to-zinc-950', tags: ['dark', 'monochrome', 'mysterious'] },
    foggy_hills_mono: { id: 'foggy_hills_mono', name: 'Ghostly Hills', bg: '/themes/images/foggyhillsmonochrome.webp', bubbles: 'from-slate-600 to-slate-900', tags: ['dark', 'monochrome', 'nature'] },
    hand_glass: { id: 'hand_glass', name: 'Trapped', bg: '/themes/images/handonglassmonochrome.webp', bubbles: 'from-neutral-800 to-black', tags: ['dark', 'monochrome', 'mysterious'] },
    man_window_mono: { id: 'man_window_mono', name: 'Observation', bg: '/themes/images/manbywindowsmonocrhome.webp', bubbles: 'from-gray-600 to-gray-900', tags: ['dark', 'monochrome', 'portrait'] },
    merry_go_round: { id: 'merry_go_round', name: 'Midnight Carousel', bg: '/themes/images/merrygoroundmonochrome.webp', bubbles: 'from-zinc-700 to-black', tags: ['dark', 'monochrome', 'creepy'] },
    mumbai_mono: { id: 'mumbai_mono', name: 'Mumbai Noir', bg: '/themes/images/mumbaimonochrome.webp', bubbles: 'from-slate-700 to-slate-950', tags: ['dark', 'monochrome', 'urban'] },
    newspaper_mono: { id: 'newspaper_mono', name: 'The Daily Noir', bg: '/themes/images/newspapermonochrome.webp', bubbles: 'from-stone-600 to-stone-900', tags: ['dark', 'monochrome', 'art'] },
    dark_man_smoke: { id: 'dark_man_smoke', name: 'Smoking Shadows', bg: '/themes/images/darkmansmokemonochrome.webp', bubbles: 'from-gray-700 to-gray-950', tags: ['dark', 'monochrome', 'portrait'] },

    
    foggy_forest: { id: 'foggy_forest', name: 'Foggy Forest', bg: '/themes/images/darkfoggyforest.webp', bubbles: 'from-emerald-800 to-teal-950', tags: ['dark', 'forest', 'nature'] },
    pine_forest: { id: 'pine_forest', name: 'Dark Pines', bg: '/themes/images/darkfoggypineforest.webp', bubbles: 'from-teal-800 to-cyan-950', tags: ['dark', 'forest', 'nature'] },
    mono_forest: { id: 'mono_forest', name: 'Midnight Woods', bg: '/themes/images/darkforestmonochrome.webp', bubbles: 'from-slate-700 to-slate-950', tags: ['dark', 'forest', 'monochrome'] },
    dark_green_forest: { id: 'dark_green_forest', name: 'Emerald Night', bg: '/themes/images/darkgreenforestnight.webp', bubbles: 'from-green-700 to-emerald-950', tags: ['dark', 'forest', 'night'] },
    calm_forest: { id: 'calm_forest', name: 'Calm Woods', bg: '/themes/images/calmforesttrees.webp', bubbles: 'from-emerald-600 to-green-900', tags: ['nature', 'forest', 'peaceful'] },
    green_grassland: { id: 'green_grassland', name: 'Serene Pasture', bg: '/themes/images/calmgreengrassland.webp', bubbles: 'from-lime-600 to-green-800', tags: ['nature', 'peaceful'] },
    dark_forest_path: { id: 'dark_forest_path', name: 'Shadow Path', bg: '/themes/images/darkforesttreespath.webp', bubbles: 'from-teal-900 to-slate-950', tags: ['dark', 'forest', 'mysterious'] },
    forest_stream: { id: 'forest_stream', name: 'Hidden Stream', bg: '/themes/images/foresthillstream.webp', bubbles: 'from-emerald-500 to-teal-800', tags: ['nature', 'water', 'forest'] },
    forest_lake: { id: 'forest_lake', name: 'Mirror Lake', bg: '/themes/images/forestlake.webp', bubbles: 'from-cyan-600 to-blue-900', tags: ['nature', 'water', 'forest'] },
    muddy_path: { id: 'muddy_path', name: 'Muddy Trail', bg: '/themes/images/forestmuddypath.webp', bubbles: 'from-amber-800 to-stone-900', tags: ['nature', 'forest', 'path'] },
    forest_path: { id: 'forest_path', name: 'Woodland Path', bg: '/themes/images/forestpath.webp', bubbles: 'from-green-600 to-emerald-900', tags: ['nature', 'forest', 'path'] },
    colorful_forest: { id: 'colorful_forest', name: 'Vibrant Woods', bg: '/themes/images/forestpathcolorful.webp', bubbles: 'from-rose-500 to-orange-700', tags: ['nature', 'colorful', 'forest'] },
    forest_stairs: { id: 'forest_stairs', name: 'Ancient Steps', bg: '/themes/images/foreststairs.webp', bubbles: 'from-stone-600 to-emerald-900', tags: ['nature', 'forest', 'mysterious'] },
    mono_trail: { id: 'mono_trail', name: 'Ghostly Trail', bg: '/themes/images/foresttrailmonochrome.webp', bubbles: 'from-slate-500 to-slate-800', tags: ['monochrome', 'forest', 'path'] },
    trees_path: { id: 'trees_path', name: 'Into the Woods', bg: '/themes/images/foresttreespath.webp', bubbles: 'from-emerald-700 to-green-950', tags: ['nature', 'forest', 'path'] },
    green_nature: { id: 'green_nature', name: 'Pure Nature', bg: '/themes/images/greennature.webp', bubbles: 'from-lime-500 to-emerald-800', tags: ['nature', 'peaceful'] },
    pine_lake: { id: 'pine_lake', name: 'Alpine Lake', bg: '/themes/images/pinetreeslake.webp', bubbles: 'from-cyan-700 to-slate-900', tags: ['nature', 'water', 'forest'] },
    river_pine: { id: 'river_pine', name: 'River Pines', bg: '/themes/images/riverpineforest.webp', bubbles: 'from-teal-600 to-cyan-900', tags: ['nature', 'water', 'forest'] },
    tree_day: { id: 'tree_day', name: 'Sunny Canopy', bg: '/themes/images/treeday.webp', bubbles: 'from-lime-500 to-green-700', tags: ['nature', 'peaceful', 'daylight'] },
    tree_lake: { id: 'tree_lake', name: 'Flooded Tree', bg: '/themes/images/treeinlake.webp', bubbles: 'from-cyan-600 to-blue-800', tags: ['nature', 'water', 'peaceful'] },
    yellow_leaves: { id: 'yellow_leaves', name: 'Autumn Leaves', bg: '/themes/images/yellowleaves.webp', bubbles: 'from-yellow-500 to-amber-700', tags: ['nature', 'colorful', 'autumn'] },
    man_rainy_forest: { id: 'man_rainy_forest', name: 'Rainy Hike', bg: '/themes/images/manrainyforest.webp', bubbles: 'from-slate-600 to-teal-900', tags: ['nature', 'forest', 'moody'] },

    
    neon_basement: { id: 'neon_basement', name: 'Neon Basement', bg: '/themes/images/neonbasement.webp', bubbles: 'from-fuchsia-600 to-purple-900', tags: ['neon', 'urban', 'dark'] },
    neon_city: { id: 'neon_city', name: 'Cyber City', bg: '/themes/images/neoncitylightsdarknight.webp', bubbles: 'from-cyan-600 to-blue-900', tags: ['neon', 'urban', 'night'] },
    neon_street: { id: 'neon_street', name: 'Neon Street', bg: '/themes/images/neonstreet.webp', bubbles: 'from-pink-600 to-rose-900', tags: ['neon', 'urban', 'street'] },
    neon_building: { id: 'neon_building', name: 'Foggy Neon', bg: '/themes/images/neonbuildingfoggylights.webp', bubbles: 'from-purple-500 to-indigo-900', tags: ['neon', 'urban', 'night'] },
    neon_sign: { id: 'neon_sign', name: 'Neon Sign', bg: '/themes/images/neongirlsjustwannahavefun.webp', bubbles: 'from-pink-500 to-rose-800', tags: ['neon', 'urban', 'colorful'] },
    neon_store: { id: 'neon_store', name: 'Cyber Store', bg: '/themes/images/neonstore.webp', bubbles: 'from-cyan-500 to-blue-800', tags: ['neon', 'urban', 'night'] },
    busy_street: { id: 'busy_street', name: 'City Rush', bg: '/themes/images/footpathbusystreet.webp', bubbles: 'from-amber-600 to-stone-900', tags: ['urban', 'street', 'daylight'] },
    river_bridge: { id: 'river_bridge', name: 'Bridge City', bg: '/themes/images/riverbridgestreet.webp', bubbles: 'from-slate-600 to-slate-900', tags: ['urban', 'architecture', 'water'] },
    train_mountain: { id: 'train_mountain', name: 'Alpine Express', bg: '/themes/images/trainmountain.webp', bubbles: 'from-stone-500 to-slate-800', tags: ['urban', 'nature', 'travel'] },
    museum_dome: { id: 'museum_dome', name: 'Museum Dome', bg: '/themes/images/mueseumpaintingsundome.webp', bubbles: 'from-amber-700 to-yellow-900', tags: ['urban', 'architecture', 'art'] },
    stadium_view: { id: 'stadium_view', name: 'Night Match', bg: '/themes/images/footballstadiumaudienceview.webp', bubbles: 'from-green-600 to-emerald-900', tags: ['urban', 'night', 'lifestyle'] },
    sunny_bedroom: { id: 'sunny_bedroom', name: 'Morning Room', bg: '/themes/images/sunnybedroom.webp', bubbles: 'from-amber-300 to-orange-500', tags: ['lifestyle', 'peaceful', 'daylight'] },
    tower_sky_mono: { id: 'tower_sky_mono', name: 'Monochrome Tower', bg: '/themes/images/towerskymonochrome.webp', bubbles: 'from-slate-500 to-slate-800', tags: ['urban', 'monochrome', 'architecture'] },
    tall_towers_mono: { id: 'tall_towers_mono', name: 'Towering Shadows', bg: '/themes/images/talltowersmonohcrome.webp', bubbles: 'from-zinc-600 to-zinc-900', tags: ['urban', 'monochrome', 'architecture'] },

    
    galaxy: { id: 'galaxy', name: 'Deep Galaxy', bg: '/themes/images/beautifulgalaxy.webp', bubbles: 'from-indigo-600 to-purple-900', tags: ['space', 'cosmic', 'colorful'] },
    smoky_nebula: { id: 'smoky_nebula', name: 'Smoky Nebula', bg: '/themes/images/beautifulsmokynebula.webp', bubbles: 'from-purple-500 to-fuchsia-800', tags: ['space', 'cosmic', 'abstract'] },
    aurora_night: { id: 'aurora_night', name: 'Aurora Night', bg: '/themes/images/beautifulauroranight.webp', bubbles: 'from-teal-500 to-emerald-800', tags: ['space', 'night', 'aurora'] },
    milky_way: { id: 'milky_way', name: 'Milky Way', bg: '/themes/images/milkywaygalaxy.webp', bubbles: 'from-blue-700 to-indigo-950', tags: ['space', 'cosmic', 'night'] },
    nebula_star: { id: 'nebula_star', name: 'Nebula Star', bg: '/themes/images/nebulastar.webp', bubbles: 'from-violet-700 to-fuchsia-950', tags: ['space', 'cosmic', 'dark'] },
    moon_clouds: { id: 'moon_clouds', name: 'Moonlit Clouds', bg: '/themes/images/moonskycloudssky.webp', bubbles: 'from-slate-600 to-slate-900', tags: ['space', 'sky', 'night'] },
    star_man: { id: 'star_man', name: 'Stargazer', bg: '/themes/images/colorfulskyfullofstarsmanstanding.webp', bubbles: 'from-cyan-600 to-violet-800', tags: ['space', 'art', 'colorful'] },
    aurora_snow: { id: 'aurora_snow', name: 'Winter Aurora', bg: '/themes/images/aurorasnow.webp', bubbles: 'from-cyan-500 to-blue-800', tags: ['space', 'aurora', 'nature'] },
    blue_aurora: { id: 'blue_aurora', name: 'Blue Aurora', bg: '/themes/images/blueaurorasky.webp', bubbles: 'from-blue-500 to-indigo-800', tags: ['space', 'aurora', 'sky'] },
    purple_nebula: { id: 'purple_nebula', name: 'Purple Nebula', bg: '/themes/images/nebula.webp', bubbles: 'from-fuchsia-600 to-purple-900', tags: ['space', 'cosmic', 'colorful'] },
    night_sky_trees: { id: 'night_sky_trees', name: 'Starry Pines', bg: '/themes/images/nightskytrees.webp', bubbles: 'from-indigo-800 to-slate-950', tags: ['space', 'nature', 'night'] },
    plane_clouds: { id: 'plane_clouds', name: 'Crimson Skies', bg: '/themes/images/aeroplaneblueredclouds.webp', bubbles: 'from-rose-500 to-red-800', tags: ['sky', 'travel', 'colorful'] },
    plane_sky: { id: 'plane_sky', name: 'Clear Skies', bg: '/themes/images/aeroplaneinthesky.webp', bubbles: 'from-sky-400 to-blue-700', tags: ['sky', 'travel', 'daylight'] },
    plane_towers: { id: 'plane_towers', name: 'City Flight', bg: '/themes/images/aeroplanetowerscenter.webp', bubbles: 'from-slate-400 to-slate-700', tags: ['sky', 'travel', 'urban'] },
    towers_sky: { id: 'towers_sky', name: 'Tower Flight', bg: '/themes/images/towersskyplane.webp', bubbles: 'from-cyan-500 to-blue-800', tags: ['sky', 'travel', 'urban'] },
    aeroplane_sky_mono: { id: 'aeroplane_sky_mono', name: 'Aviation Noir', bg: '/themes/images/aeroplaneskytowermonochrome.webp', bubbles: 'from-gray-500 to-gray-800', tags: ['sky', 'monochrome', 'travel'] },

    
    volcano_smoke: { id: 'volcano_smoke', name: 'Volcanic Ash', bg: '/themes/images/volcanosmoke.webp', bubbles: 'from-red-800 to-orange-950', tags: ['nature', 'moody', 'epic'] },
    foggy_sunset: { id: 'foggy_sunset', name: 'Blood Horizon', bg: '/themes/images/beautifulfoggysunsetforest.webp', bubbles: 'from-orange-700 to-red-950', tags: ['nature', 'sunset', 'moody'] },
    violet_beach: { id: 'violet_beach', name: 'Violet Shores', bg: '/themes/images/violetsunsetbeachtrees.webp', bubbles: 'from-violet-600 to-purple-900', tags: ['nature', 'sunset', 'water'] },
    sunset_pine: { id: 'sunset_pine', name: 'Sunset Pines', bg: '/themes/images/sunsetpineforest.webp', bubbles: 'from-amber-700 to-orange-950', tags: ['nature', 'sunset', 'forest'] },
    plane_sunset: { id: 'plane_sunset', name: 'Sunset Takeoff', bg: '/themes/images/aeroplanetakeoffsunset.webp', bubbles: 'from-orange-500 to-red-800', tags: ['sunset', 'travel', 'sky'] },
    blue_sunset: { id: 'blue_sunset', name: 'Twilight Blue', bg: '/themes/images/bluecolourfulaftersunset.webp', bubbles: 'from-blue-600 to-indigo-900', tags: ['sunset', 'sky', 'colorful'] },
    blue_fog_tree: { id: 'blue_fog_tree', name: 'Foggy Twilight', bg: '/themes/images/bluefoggysunsettree.webp', bubbles: 'from-cyan-700 to-blue-950', tags: ['sunset', 'nature', 'moody'] },
    clouds_sunset: { id: 'clouds_sunset', name: 'Golden Clouds', bg: '/themes/images/cloudssunset.webp', bubbles: 'from-amber-500 to-orange-800', tags: ['sunset', 'sky', 'colorful'] },
    colorful_sunset: { id: 'colorful_sunset', name: 'Vibrant Sunset', bg: '/themes/images/colorfulsunsetforest.webp', bubbles: 'from-rose-500 to-purple-800', tags: ['sunset', 'nature', 'colorful'] },
    dark_brook: { id: 'dark_brook', name: 'Evening Brook', bg: '/themes/images/darkeveningbrook.webp', bubbles: 'from-slate-700 to-slate-950', tags: ['nature', 'water', 'dark'] },
    evening_brook: { id: 'evening_brook', name: 'Dusk Brook', bg: '/themes/images/eveningbrook.webp', bubbles: 'from-emerald-700 to-teal-950', tags: ['nature', 'water', 'sunset'] },
    hikers_sunset: { id: 'hikers_sunset', name: 'Sunset Hike', bg: '/themes/images/hikerssunsettrees.webp', bubbles: 'from-orange-600 to-red-900', tags: ['nature', 'sunset', 'lifestyle'] },
    hiking_lake: { id: 'hiking_lake', name: 'Alpine Trek', bg: '/themes/images/hikinglakehillsman.webp', bubbles: 'from-cyan-600 to-blue-900', tags: ['nature', 'water', 'lifestyle'] },
    hiking_man: { id: 'hiking_man', name: 'Mountain Trek', bg: '/themes/images/hikingman.webp', bubbles: 'from-stone-500 to-stone-800', tags: ['nature', 'lifestyle', 'epic'] },
    castle_view: { id: 'castle_view', name: 'Castle Horizon', bg: '/themes/images/hillsfromcastleview.webp', bubbles: 'from-emerald-600 to-green-900', tags: ['nature', 'epic', 'architecture'] },
    snowy_mountains: { id: 'snowy_mountains', name: 'Alpine Peaks', bg: '/themes/images/snowymountains.webp', bubbles: 'from-slate-300 to-slate-600', tags: ['nature', 'epic', 'snow'] },
    snowy_pines: { id: 'snowy_pines', name: 'Winter Pines', bg: '/themes/images/snowymountainspines.webp', bubbles: 'from-sky-600 to-slate-800', tags: ['nature', 'forest', 'snow'] },
    sunrise_hills: { id: 'sunrise_hills', name: 'Golden Hills', bg: '/themes/images/sunrisehills.webp', bubbles: 'from-amber-400 to-orange-700', tags: ['nature', 'sunrise', 'colorful'] },
    sunrise_path: { id: 'sunrise_path', name: 'Dawn Trail', bg: '/themes/images/sunrisehillspath.webp', bubbles: 'from-orange-400 to-red-700', tags: ['nature', 'sunrise', 'path'] },
    sunrise_tree: { id: 'sunrise_tree', name: 'Dawn Meadow', bg: '/themes/images/sunrisetreegrassland.webp', bubbles: 'from-yellow-500 to-amber-700', tags: ['nature', 'sunrise', 'peaceful'] },
    sunrise_valley: { id: 'sunrise_valley', name: 'Morning Valley', bg: '/themes/images/sunrisevalley.webp', bubbles: 'from-emerald-500 to-teal-800', tags: ['nature', 'sunrise', 'epic'] },
    sunset_eagle: { id: 'sunset_eagle', name: 'Eagle Sunset', bg: '/themes/images/sunsetbeacheagle.webp', bubbles: 'from-orange-600 to-red-900', tags: ['nature', 'sunset', 'animals'] },
    sunset_desert: { id: 'sunset_desert', name: 'Desert Dusk', bg: '/themes/images/sunsetdesertcliff.webp', bubbles: 'from-amber-700 to-orange-950', tags: ['nature', 'sunset', 'epic'] },
    sunset_field: { id: 'sunset_field', name: 'Golden Field', bg: '/themes/images/sunsetfield.webp', bubbles: 'from-yellow-600 to-orange-800', tags: ['nature', 'sunset', 'peaceful'] },
    sunset_hills: { id: 'sunset_hills', name: 'Dusk Hills', bg: '/themes/images/sunsethills.webp', bubbles: 'from-rose-500 to-red-800', tags: ['nature', 'sunset', 'epic'] },
    sunset_mountain: { id: 'sunset_mountain', name: 'Mountain Dusk', bg: '/themes/images/sunsetmountain.webp', bubbles: 'from-purple-600 to-indigo-900', tags: ['nature', 'sunset', 'epic'] },
    sunset_valley: { id: 'sunset_valley', name: 'Valley Dusk', bg: '/themes/images/sunsetvalley.webp', bubbles: 'from-fuchsia-600 to-purple-900', tags: ['nature', 'sunset', 'colorful'] },

    
    rainbow_waterfall: { id: 'rainbow_waterfall', name: 'Prism Falls', bg: '/themes/images/rainbowwaterfall.webp', bubbles: 'from-emerald-600 to-teal-800', tags: ['water', 'nature', 'colorful'] },
    archipelago: { id: 'archipelago', name: 'Island Chain', bg: '/themes/images/archipelago.webp', bubbles: 'from-cyan-500 to-blue-800', tags: ['water', 'nature', 'epic'] },
    italian_cliff: { id: 'italian_cliff', name: 'Coastal Cliff', bg: '/themes/images/beautifulhillyoceancliffitaly.webp', bubbles: 'from-sky-500 to-blue-800', tags: ['water', 'nature', 'travel'] },
    ocean_woman_mono: { id: 'ocean_woman_mono', name: 'Ocean Silhouette', bg: '/themes/images/beautifulwomanoceanmonochrome.webp', bubbles: 'from-slate-500 to-slate-800', tags: ['water', 'monochrome', 'portrait'] },
    cliff_day: { id: 'cliff_day', name: 'Sunny Cliff', bg: '/themes/images/cliffday.webp', bubbles: 'from-sky-400 to-blue-600', tags: ['nature', 'epic', 'daylight'] },
    cliff_stream: { id: 'cliff_stream', name: 'Cliff Stream', bg: '/themes/images/cliffrivrestream.webp', bubbles: 'from-emerald-500 to-teal-700', tags: ['water', 'nature', 'epic'] },
    cliff_beach: { id: 'cliff_beach', name: 'Beach Cliffs', bg: '/themes/images/cliffsbeach.webp', bubbles: 'from-cyan-600 to-blue-900', tags: ['water', 'nature', 'epic'] },
    day_cliffs: { id: 'day_cliffs', name: 'Daylight Cliffs', bg: '/themes/images/daycliffs.webp', bubbles: 'from-blue-500 to-indigo-800', tags: ['nature', 'epic', 'daylight'] },
    day_hills: { id: 'day_hills', name: 'Green Hills', bg: '/themes/images/dayhills.webp', bubbles: 'from-lime-500 to-green-700', tags: ['nature', 'peaceful', 'daylight'] },
    day_tall_tree: { id: 'day_tall_tree', name: 'Skyward Canopy', bg: '/themes/images/daytalltreesky.webp', bubbles: 'from-emerald-500 to-green-800', tags: ['nature', 'forest', 'daylight'] },
    day_trees: { id: 'day_trees', name: 'Sunny Canopy', bg: '/themes/images/daytrees.webp', bubbles: 'from-green-500 to-emerald-700', tags: ['nature', 'forest', 'daylight'] },
    desert_cliffs: { id: 'desert_cliffs', name: 'Canyon Walls', bg: '/themes/images/desertcliffs.webp', bubbles: 'from-amber-600 to-orange-800', tags: ['nature', 'epic', 'desert'] },
    huge_waterfall: { id: 'huge_waterfall', name: 'Mighty Falls', bg: '/themes/images/hugewaterfall.webp', bubbles: 'from-cyan-600 to-blue-900', tags: ['water', 'nature', 'epic'] },
    cliff_jump: { id: 'cliff_jump', name: 'Ocean Leap', bg: '/themes/images/jumpingoffclifftoocean.webp', bubbles: 'from-sky-500 to-blue-800', tags: ['water', 'lifestyle', 'epic'] },
    ocean_cliffs: { id: 'ocean_cliffs', name: 'Sea Cliffs', bg: '/themes/images/oceancliffs.webp', bubbles: 'from-blue-600 to-indigo-900', tags: ['water', 'nature', 'epic'] },
    sunrise_islands: { id: 'sunrise_islands', name: 'Sunrise Islands', bg: '/themes/images/sunrisearchipaelego.webp', bubbles: 'from-rose-400 to-orange-600', tags: ['water', 'sunrise', 'epic'] },
    sunset_bridge: { id: 'sunset_bridge', name: 'Ocean Bridge', bg: '/themes/images/sunsetbridgeocean.webp', bubbles: 'from-orange-500 to-red-800', tags: ['water', 'sunset', 'architecture'] },
    sunset_ocean: { id: 'sunset_ocean', name: 'Ocean Dusk', bg: '/themes/images/sunsetocean.webp', bubbles: 'from-violet-500 to-purple-800', tags: ['water', 'sunset', 'peaceful'] },
    sunset_waterfall: { id: 'sunset_waterfall', name: 'Falls Dusk', bg: '/themes/images/sunsetwaterfall.webp', bubbles: 'from-rose-600 to-red-900', tags: ['water', 'sunset', 'nature'] },
    waterfall_bridge: { id: 'waterfall_bridge', name: 'Bridge Falls', bg: '/themes/images/waterfallbridge.webp', bubbles: 'from-emerald-600 to-teal-900', tags: ['water', 'nature', 'architecture'] },
    green_waterfall: { id: 'green_waterfall', name: 'Emerald Falls', bg: '/themes/images/waterfallgreen.webp', bubbles: 'from-green-600 to-emerald-900', tags: ['water', 'nature', 'forest'] },
    waterfall_hills: { id: 'waterfall_hills', name: 'Hillside Falls', bg: '/themes/images/waterfallhills.webp', bubbles: 'from-teal-500 to-cyan-800', tags: ['water', 'nature', 'epic'] },
    water_splash: { id: 'water_splash', name: 'Ocean Splash', bg: '/themes/images/watersplash.webp', bubbles: 'from-cyan-400 to-blue-700', tags: ['water', 'nature', 'abstract'] },

    
    cute_dog: { id: 'cute_dog', name: 'Good Boy', bg: '/themes/images/beautifulcutedog.webp', bubbles: 'from-amber-500 to-orange-700', tags: ['animals', 'peaceful'] },
    beautiful_dog: { id: 'beautiful_dog', name: 'Loyal Friend', bg: '/themes/images/beautifuldog.webp', bubbles: 'from-stone-500 to-stone-700', tags: ['animals', 'peaceful'] },
    flower_valley: { id: 'flower_valley', name: 'Vibrant Valley', bg: '/themes/images/colorfulflowervalley.webp', bubbles: 'from-fuchsia-500 to-rose-700', tags: ['nature', 'floral', 'colorful'] },
    colorful_canopy: { id: 'colorful_canopy', name: 'Autumn Canopy', bg: '/themes/images/colorfulforesttreesfromtop.webp', bubbles: 'from-orange-500 to-red-700', tags: ['nature', 'forest', 'colorful'] },
    flower_hills_color: { id: 'flower_hills_color', name: 'Spring Hills', bg: '/themes/images/colourfulflowerhills.webp', bubbles: 'from-pink-500 to-rose-700', tags: ['nature', 'floral', 'colorful'] },
    cat_bed: { id: 'cat_bed', name: 'Lazy Feline', bg: '/themes/images/cutecatinbed.webp', bubbles: 'from-slate-400 to-slate-600', tags: ['animals', 'lifestyle', 'peaceful'] },
    dog_rose: { id: 'dog_rose', name: 'Romantic Pup', bg: '/themes/images/dogrosebiting.webp', bubbles: 'from-rose-500 to-red-800', tags: ['animals', 'floral', 'art'] },
    flower_hills: { id: 'flower_hills', name: 'Floral Hills', bg: '/themes/images/flowerhills.webp', bubbles: 'from-violet-500 to-purple-700', tags: ['nature', 'floral', 'peaceful'] },
    giraffe_sunset: { id: 'giraffe_sunset', name: 'Savanna Dusk', bg: '/themes/images/giraffesunsetgrassland.webp', bubbles: 'from-orange-600 to-red-900', tags: ['animals', 'sunset', 'nature'] },
    dog_flower: { id: 'dog_flower', name: 'Gentle Pup', bg: '/themes/images/gogholdingflowerinmouth.webp', bubbles: 'from-emerald-500 to-green-700', tags: ['animals', 'floral', 'peaceful'] },
    grass_flowers: { id: 'grass_flowers', name: 'Sunset Bloom', bg: '/themes/images/grassflowerssunset.webp', bubbles: 'from-amber-500 to-orange-700', tags: ['nature', 'floral', 'sunset'] },
    lotus_flower: { id: 'lotus_flower', name: 'Sacred Lotus', bg: '/themes/images/lotus.webp', bubbles: 'from-pink-400 to-rose-600', tags: ['nature', 'floral', 'peaceful'] },
    orange_cat: { id: 'orange_cat', name: 'Curious Cat', bg: '/themes/images/orangehousecatlookingup.webp', bubbles: 'from-orange-400 to-amber-700', tags: ['animals', 'lifestyle'] },
    violets_garden: { id: 'violets_garden', name: 'Violet Garden', bg: '/themes/images/violetsgarden.webp', bubbles: 'from-violet-500 to-fuchsia-700', tags: ['nature', 'floral', 'colorful'] },
    flower_brook: { id: 'flower_brook', name: 'Floral Brook', bg: '/themes/images/violetwhiteflowerbrooktrees.webp', bubbles: 'from-purple-500 to-indigo-700', tags: ['nature', 'floral', 'water'] },
    winking_dog: { id: 'winking_dog', name: 'Cheeky Pup', bg: '/themes/images/winkingdog.webp', bubbles: 'from-stone-400 to-stone-600', tags: ['animals', 'lifestyle'] },
    yellow_flower_hills: { id: 'yellow_flower_hills', name: 'Golden Blooms', bg: '/themes/images/yellowflowerhills.webp', bubbles: 'from-yellow-400 to-amber-600', tags: ['nature', 'floral', 'colorful'] },
    mono_cat_street: { id: 'mono_cat_street', name: 'Alley Cat', bg: '/themes/images/monochromecatstreet.webp', bubbles: 'from-gray-600 to-gray-900', tags: ['animals', 'monochrome', 'urban'] },


    dj_party: { id: 'dj_party', name: 'The Underground', bg: '/themes/images/djpartyaudienceview.webp', bubbles: 'from-violet-600 to-fuchsia-900', tags: ['music', 'night', 'lifestyle'] },
    guitarist_blue: { id: 'guitarist_blue', name: 'Blue Stage', bg: '/themes/images/guitaristlivestagedarkblue.webp', bubbles: 'from-blue-600 to-indigo-900', tags: ['music', 'dark', 'concert'] },
    drummer_stage: { id: 'drummer_stage', name: 'The Drummer', bg: '/themes/images/drummerstage.webp', bubbles: 'from-rose-600 to-red-900', tags: ['music', 'concert', 'dark'] },
    psychedelia: { id: 'psychedelia', name: 'Psychedelia', bg: '/themes/images/bluewhitepsychedelia.webp', bubbles: 'from-sky-500 to-blue-800', tags: ['art', 'colorful', 'music'] },
    band_live: { id: 'band_live', name: 'Live Show', bg: '/themes/images/bandlivestageshow.webp', bubbles: 'from-purple-600 to-indigo-900', tags: ['music', 'concert', 'lifestyle'] },
    girl_keyboard: { id: 'girl_keyboard', name: 'Keys & Chords', bg: '/themes/images/beautifulgirlkeyboard.webp', bubbles: 'from-pink-500 to-rose-800', tags: ['music', 'lifestyle', 'portrait'] },
    drummer_rehearsal: { id: 'drummer_rehearsal', name: 'Studio Session', bg: '/themes/images/drummerrehearsalstudio.webp', bubbles: 'from-stone-600 to-stone-900', tags: ['music', 'lifestyle', 'dark'] },
    guitar_amp: { id: 'guitar_amp', name: 'Living Room Amp', bg: '/themes/images/guitaramplivingroom.webp', bubbles: 'from-amber-700 to-stone-900', tags: ['music', 'lifestyle', 'peaceful'] },
    guitarist_live: { id: 'guitarist_live', name: 'Center Stage', bg: '/themes/images/guitaristlivestageshow.webp', bubbles: 'from-emerald-600 to-teal-900', tags: ['music', 'concert', 'lifestyle'] },
    guitar_friends: { id: 'guitar_friends', name: 'Acoustic Jam', bg: '/themes/images/guitarplayingfriendslivingroom.webp', bubbles: 'from-orange-500 to-red-700', tags: ['music', 'lifestyle', 'peaceful'] },
    guitar_store: { id: 'guitar_store', name: 'The Guitar Shop', bg: '/themes/images/guitarstorerack.webp', bubbles: 'from-amber-600 to-yellow-900', tags: ['music', 'lifestyle', 'urban'] },
    library_girl: { id: 'library_girl', name: 'Quiet Study', bg: '/themes/images/librarybooksgirl.webp', bubbles: 'from-stone-500 to-stone-800', tags: ['lifestyle', 'peaceful', 'portrait'] },
    livingroom_studio: { id: 'livingroom_studio', name: 'Home Studio', bg: '/themes/images/livingroomguitarkeyboards.webp', bubbles: 'from-slate-600 to-slate-900', tags: ['music', 'lifestyle', 'peaceful'] },
    window_man: { id: 'window_man', name: 'Contemplation', bg: '/themes/images/windowmancenter.webp', bubbles: 'from-blue-700 to-indigo-950', tags: ['lifestyle', 'portrait', 'moody'] },
};